# Generated by Django 4.2.4 on 2023-09-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_message_contact_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mensaje',
            new_name='message',
        ),
    ]
