# Generated by Django 4.2.4 on 2023-09-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_rename_mensaje_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Precio del auto'),
            preserve_default=False,
        ),
    ]
