# Generated by Django 4.2.4 on 2023-09-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='car_price',
            field=models.IntegerField(verbose_name='Precio del auto'),
        ),
    ]
