# Generated by Django 4.2.4 on 2023-09-03 12:33

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('state', models.CharField(choices=[('BN', 'Beni'), ('CB', 'Cochabamba'), ('CH', 'Chuquisaca'), ('LP', 'La Paz'), ('OR', 'Oruro'), ('PN', 'Pando'), ('PT', 'Potosí'), ('TJ', 'Tarija'), ('SC', 'Santa Cruz')], max_length=100, verbose_name='Departamento')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], verbose_name='Año')),
                ('condition', models.CharField(max_length=100, verbose_name='Condición')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('photo', models.ImageField(upload_to='photos/cars/%Y/%m/%d/', verbose_name='Foto destacada')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Foto 1')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Foto 2')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Foto 3')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Foto 4')),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Control de crucero', 'Control de crucero'), ('Interfaz de audio', 'Interfaz de audio'), ('Airbags', 'Airbags'), ('Aire acondicionado', 'Aire acondicionado'), ('Calefacción de asientos', 'Calefacción de asientos'), ('Sistema de alarma', 'Sistema de alarma'), ('Asistente de estacionamiento', 'Asistente de estacionamiento'), ('Dirección asistida', 'Dirección asistida'), ('Cámara de retroceso', 'Cámara de retroceso'), ('Inyección directa de combustible', 'Inyección directa de combustible'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Deflector de viento', 'Deflector de viento'), ('Teléfono Bluetooth', 'Teléfono Bluetooth')], max_length=255, verbose_name='Características')),
                ('body_style', models.CharField(max_length=100, verbose_name='Estilo de carrocería')),
                ('engine', models.CharField(max_length=100, verbose_name='Motor')),
                ('transmission', models.CharField(max_length=100, verbose_name='Transmisión')),
                ('interior', models.CharField(max_length=100, verbose_name='Interior')),
                ('kilometres', models.IntegerField(verbose_name='Kilómetros')),
                ('doors', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, verbose_name='Puertas')),
                ('passengers', models.IntegerField(verbose_name='Pasajeros')),
                ('vin_no', models.CharField(max_length=100, verbose_name='Chasis')),
                ('kilometraje', models.IntegerField(verbose_name='Kilometraje')),
                ('fuel_type', models.CharField(max_length=50, verbose_name='Combustible')),
                ('no_of_owners', models.CharField(max_length=100, verbose_name='Propietarios')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Autos',
            },
        ),
    ]
