# Generated by Django 4.2.4 on 2023-09-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Audi', 'Audi'), ('Subaru', 'Subaru'), ('Changan', 'Changan'), ('JAC', 'JAC'), ('Suzuki', 'Suzuki'), ('Renault', 'Renault'), ('Tesla', 'Tesla'), ('Volkswagen', 'Volkswagen'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia')], default='Toyota', max_length=100, verbose_name='Marca'),
            preserve_default=False,
        ),
    ]
