# Generated by Django 4.2.4 on 2023-09-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='normal_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio normal'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Audi', 'Audi'), ('Changan', 'Changan'), ('Ferrari', 'Ferrari'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('JAC', 'JAC'), ('Jaguar', 'Jaguar'), ('Kia', 'Kia'), ('Lamborghini', 'Lamborghini'), ('Nissan', 'Nissan'), ('Porche', 'Porche'), ('Renault', 'Renault'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(verbose_name='Precio de oferta'),
        ),
    ]
