# Generated by Django 4.2.4 on 2023-09-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_normal_price_alter_car_brand_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='normal_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio regular'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
