# Generated by Django 4.2.4 on 2023-09-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('designation', models.CharField(max_length=255, verbose_name='Cargo')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Foto')),
                ('facebook_link', models.URLField(max_length=255, verbose_name='Facebook')),
                ('twitter_link', models.URLField(max_length=255, verbose_name='Twitter')),
                ('instagram_link', models.URLField(max_length=255, verbose_name='Instagram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
